# Site settings
title: Stefan Keselj's Work
email: 
description: "This layout was copied from Andrej Karpathy's <a href='http://karpathy.github.io/'>site</a>"
baseurl: ""
url: "http://skeselj.github.io"
twitter_username: skeselj
github_username:  skeselj

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
